[project]
name = "sparkling-api"
version = "0.1.0"
description = "Prompting Pipeline API (MVP)"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.6",
]

[tool.uvicorn]
factory = false
host = "0.0.0.0"
port = 8000
reload = true
