[project]
name = "sparkling-api"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic>=2",
]

[project.optional-dependencies]
dev = ["pytest", "httpx"]
